export { default as Swatch } from './Swatch'
export { default as ProductView } from './ProductView'
export { default as CollarView } from './CollarView'
export { default as ProductCard } from './ProductCard'
export { default as ProductSlider } from './ProductSlider'
